server:
  port: 8080
site:
  url: localhost:8080



spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    username: car_user
    password: rootan
    url: jdbc:postgresql://localhost:5432/car_db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: akbqkb780@gmail.com
    password: bauiubkecpadkhvy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000